baseURL               = "https://user.moely.link/"
languageCode          = "zh-CN"
title                 = "萌哩用户中心"
theme                 = "usercenter"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[outputs]
home = ["HTML", "JSON"]

[params]
    author        = "萌哩（moely）"
    description   = "萌哩（moely）用户中心。用户可以登陆账号并在此处修改账号信息，绑定第三方账号登录方式，使用收藏列表等特色功能。"

[params.images]
    favicon       = "/img/favicon.png"

[markup.goldmark.renderer]
    unsafe = true
